version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/zheeeng/pagination
    steps:
      - checkout
      - run: go get github.com/mattn/goveralls
      - run:
          name: "Create a temp directory for artifacts"
          command: |
            mkdir -p /tmp/artifacts
      - run:
          name: Run unit tests with coverage
          command: |
            go test -coverprofile=c.out ./...
            go tool cover -html=c.out -o coverage.html
            mv coverage.html /tmp/artifacts
      - run:
          command: $GOPATH/bin/goveralls -coverprofile=c.out -service=circle-ci -repotoken=$COVERALLS_REPO_TOKEN
      - store_artifacts:
          path: /tmp/artifacts
